### ISSUE TITLE
Video in Home  wird nicht gespielt

### ISSUE THREAD

**Issue by h-fares** [HSKE-Streaming-Server/media-streaming-client#10]
wenn man Video in Home auswählt, geht nur bis "play now" aber wird nicht gespielt.

**Comment by FlorianBirk** [comment]
Ich hab da bis jetzt einfach immer das ganze object in den cookie, würde das aber gerne sauberer lösen. Dafür bräuchte ich einen zusätzlichen post-request in der API.


## `post` http://serveradress/detail

`body`:

```
{
        'token': string
	'streamId': string
}
```


`response`: 

```
{
	'id':string, (GUID)
	'name':string,
	'image':string,
	'type':string,
	'description':string,
	...
}
```


hab den auch schon mal in der API-Doku hinzugefügt....könnte den jmnd von den Server-Leuten umsetzen?

**Comment by niklasstich** [comment]
Implementiert in https://github.com/HSKE-Streaming-Server/media-streaming-server/pull/21
